apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-12-30T16:37:51Z"
  labels:
    kops.k8s.io/cluster: kopscluster.researchkernel.org
  name: elk
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t3.medium
  maxPrice: "0.0125"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: elk
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  - us-east-1e
  - us-east-1f
